### ISSUE TITLE
suggest to apply iNaturalist taxon color scheme to indicate taxonomic context

### ISSUE THREAD

**Issue by jhpoelen** [globalbioticinteractions/globalbioticinteractions.github.io#41]
To help identify taxa, @KatjaSchulz et al. suggested to apply iNaturalist color schemes in the GloBI pages.

![screen shot 2015-08-20 at 2 45 28 pm](https://cloud.githubusercontent.com/assets/1084872/9396468/21b48dd8-474a-11e5-9f06-084c048caf24.png)

**Comment by jhpoelen** [comment]
Color scheme from https://github.com/inaturalist/inaturalist/blob/master/app/assets/stylesheets/lists.css.scss#L160 :

```css
.Protozoa,        .stat.Protozoa a        { color: #691776;  }
.Plantae,         .stat.Plantae a         { color: #73AC13;  }
.Fungi,           .stat.Fungi a           { color: DeepPink; }
.Animalia,        .stat.Animalia a        { color: #1E90FF;  }
.Mollusca,        .stat.Mollusca a        { color: #FF4500;  }
.Arachnida,       .stat.Arachnida a       { color: #FF4500;  }
.Insecta,         .stat.Insecta a         { color: #FF4500;  }
.Amphibia,        .stat.Amphibia a        { color: #1E90FF;  }
.Reptilia,        .stat.Reptilia a        { color: #1E90FF;  }
.Aves,            .stat.Aves a            { color: #1E90FF;  }
.Mammalia,        .stat.Mammalia a        { color: #1E90FF;  }
.Actinopterygii,  .stat.Actinopterygii a  { color: #1E90FF;  }
.Chromista,       .stat.Chromista a  { color: #993300;  }

.Protozoa:hover  { color: #691776;  }
.Plantae:hover   { color: #73AC13;  }
.Fungi:hover     { color: DeepPink; }
.Animalia:hover  { color: #1E90FF;  }
.Mollusca:hover  { color: #FF4500;  }
.Arachnida:hover { color: #FF4500;  }
.Insecta:hover   { color: #FF4500;  }
.Amphibia:hover  { color: #1E90FF;  }
.Reptilia:hover  { color: #1E90FF;  }
.Aves:hover      { color: #1E90FF;  }
.Mammalia:hover  { color: #1E90FF;  }
.Actinopterygii:hover  { color: #1E90FF;  }
.Chromista:hover  { color: #993300;  }
```
